version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/randomactivity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1693
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1693
      POSTGRES_DB: randomactivity
    ports:
      - "5433:5433"
    networks:
      - app-network

networks:
  app-network:
